# ANN (Artificial Neural Networks) with Scikit Learn
 
Neural Networks are a machine learning framework that attempts to mimic the learning pattern of natural biological neural networks. Biological neural networks have interconnected neurons with dendrites that receive inputs, then based on these inputs they produce an output signal through an axon to another neuron. We will try to mimic this process through the use of Artificial Neural Networks (ANN), which we will just refer to as neural networks from now on. The process of creating a neural network begins with the most basic form, a single perceptron.

The Perceptron
 
Let's start our discussion by talking about the Perceptron! A perceptron has one or more inputs, a bias, an activation function, and a single output. The perceptron receives inputs, multiplies them by some weight, and then passes them into an activation function to produce an output. There are many possible activation functions to choose from, such as the logistic function, a trigonometric function, a step function etc. We also make sure to add a bias to the perceptron, this avoids issues where all inputs could be equal to zero (meaning no multiplicative weight would have an effect). Check out the diagram below for a visualization of a perceptron:

Once we have the output we can compare it to a known label and adjust the weights accordingly (the weights usually start off with random initialization values). We keep repeating this process until we have reached a maximum number of allowed iterations, or an acceptable error rate.

To create a neural network, we simply begin to add layers of perceptrons together, creating a multi-layer perceptron model of a neural network. You'll have an input layer which directly takes in your feature inputs and an output layer which will create the resulting outputs. Any layers in between are known as hidden layers because they don't directly "see" the feature inputs or outputs. For a visualization of this check out the diagram below (source: Wikipedia).

Let's move on to actually creating a neural network with Python!

SciKit-Learn
 
In order to follow along with this tutorial, you'll need to have the latest version of SciKit Learn installed! It is easily installable either through pip or conda, but you can reference the official installation documentation for complete details on this.

### Case Study1:  Using Inbuild Dataset (Brest Cancer data)
 
We'll use SciKit Learn's built in Breast Cancer Data Set which has several features of tumors with a labeled class indicating whether the tumor was Malignant or Benign. We will try to create a neural network model that can take in these features and attempt to predict malignant or benign labels for tumors it has not seen before. Let's go ahead and start by getting the data!

This object is like a dictionary, it contains a description of the data and the features and targets:

In [1]:
import sklearn.datasets as dt

In [2]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [3]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
print(cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [5]:
# Print full description by running:
# print(cancer['DESCR'])
# 569 data points with 30 features
cancer['data'].shape

(569, 30)

In [6]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [9]:
X = cancer['data']
y = cancer['target']
print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [10]:
import pandas as pd

In [11]:
pd.DataFrame(X).head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9   ...     20     21      22      23      24      25      26      27  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.05667  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.05999  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.09744  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.05883  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       28       29  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 30 columns]

In [12]:
y = pd.Series(y)

In [13]:
y.value_counts()

1    357
0    212
Name: count, dtype: int64

Train Test Split
 
Let's split our data into training and testing sets, this is done easily with SciKit Learn's train_test_split function from model_selection:

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

Data Preprocessing
 
The neural network may have difficulty converging before the maximum number of iterations allowed if the data is not normalized. Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data. Note that you must apply the same scaling to the test set for meaningful results. There are a lot of different methods for normalization of data, we will use the built-in StandardScaler for standardization.

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [16]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

Now it is time to train our model. SciKit Learn makes this incredibly easy, by using estimator objects. In this case we will import our estimator (the Multi-Layer Perceptron Classifier model) from the neural_network library of SciKit-Learn!

from sklearn.neural_network import MLPClassifier

In [17]:
from sklearn.neural_network import MLPClassifier

Next we create an instance of the model, there are a lot of parameters you can choose to define and customize here, we will only define the hidden_layer_sizes. For this parameter you pass in a tuple consisting of the number of neurons you want at each layer, where the nth entry in the tuple represents the number of neurons in the nth layer of the MLP model. There are many ways to choose these numbers, but for simplicity we will choose 3 layers with the same number of neurons as there are features in our data set:

In [18]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))

Now that the model has been made we can fit the training data to our model, remember that this data has already been processed and scaled:

In [20]:
mlp.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(30, 30, 30))

In [21]:
dir(mlp)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_backprop',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_solver',
 '_compute_loss_grad',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_fit',
 '_fit_lbfgs',
 '_fit_stochastic',
 '_forward_pass',
 '_forward_pass_fast',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_init_coef',
 '_initialize',
 '_label_binarizer',
 '_loss_grad_lbfgs',
 '_more_tags',
 '_no

You can see the output that shows the default values of the other parameters in the model. I encourage you to play around with them and discover what effects they have on your model!

### Predictions and Evaluation
Now that we have a model it is time to use it to get predictions! We can do this simply with the predict() method off of our fitted model:

In [22]:
predictions = mlp.predict(X_test)

Now we can use SciKit-Learn's built in metrics such as a classification report and confusion matrix to evaluate how well our model performed:

In [23]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[53  1]
 [ 0 89]]


In [24]:
mlp.predict_proba(X_test)

array([[2.29306831e-03, 9.97706932e-01],
       [4.42748482e-07, 9.99999557e-01],
       [1.00000000e+00, 1.78510229e-18],
       [9.99880432e-01, 1.19567650e-04],
       [2.03865151e-08, 9.99999980e-01],
       [9.05869644e-08, 9.99999909e-01],
       [3.06826452e-06, 9.99996932e-01],
       [1.00000000e+00, 4.17131014e-11],
       [2.30436010e-05, 9.99976956e-01],
       [3.45673587e-02, 9.65432641e-01],
       [9.99976467e-01, 2.35328865e-05],
       [3.49972332e-02, 9.65002767e-01],
       [9.99998045e-01, 1.95502722e-06],
       [2.06378909e-06, 9.99997936e-01],
       [1.00000000e+00, 1.44719200e-23],
       [2.75228158e-04, 9.99724772e-01],
       [1.00000000e+00, 9.26171642e-24],
       [1.00000000e+00, 2.08902849e-20],
       [1.31962390e-05, 9.99986804e-01],
       [6.55753109e-06, 9.99993442e-01],
       [1.96001424e-07, 9.99999804e-01],
       [1.41642800e-08, 9.99999986e-01],
       [1.00000000e+00, 1.46228620e-12],
       [1.00000000e+00, 6.68445942e-13],
       [3.587225

In [25]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        54
           1       0.99      1.00      0.99        89

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143



Looks like we only misclassified 3 tumors, leaving us with a 98% accuracy rate (as well as 98% precision and recall). This is pretty good considering how few lines of code we had to write! The downside however to using a Multi-Layer Preceptron model is how difficult it is to interpret the model itself. The weights and biases won't be easily interpretable in relation to which features are important to the model itself.

However, if you do want to extract the MLP weights and biases after training your model, you use its public attributes coefs_ and intercepts_.

coefs_ is a list of weight matrices, where weight matrix at index i represents the weights between layer i and layer i+1.

intercepts_ is a list of bias vectors, where the vector at index i represents the bias values added to layer i+1.

In [26]:
mlp.coefs_

[array([[-1.00971403e-01,  2.27439626e-01,  3.11194066e-01,
          1.73404242e-01, -8.93765732e-02,  3.69636545e-01,
          2.77888314e-01,  4.46317847e-02, -2.71046325e-01,
         -2.67741081e-01, -1.33864644e-01,  2.45579369e-01,
          9.93460770e-02, -1.62004023e-01,  8.38461905e-02,
         -1.85469546e-02,  9.29587122e-02, -2.17866094e-01,
         -4.99374783e-02,  2.06305725e-01, -1.27144897e-01,
         -2.94662312e-01, -1.91654363e-01,  1.29140532e-01,
         -9.27184087e-02,  1.37518423e-01,  2.03298881e-01,
         -1.62452441e-01,  2.92395310e-01, -2.61644977e-01],
        [ 1.65638892e-01,  2.87909747e-01,  1.00312672e-01,
          1.51148304e-01,  3.33911198e-01,  2.21349857e-01,
          1.89424358e-01, -2.92035062e-01,  2.25973795e-01,
          1.39464936e-01,  3.51075470e-01, -9.08486088e-02,
         -1.18429942e-01,  1.71509835e-01,  1.21779867e-01,
         -3.35634029e-01, -5.10506045e-03, -2.05964463e-01,
         -2.43581694e-01,  1.13946843e-

In [27]:
len(mlp.coefs_)

4

In [28]:
len(mlp.coefs_[0])

30

In [29]:
len(mlp.intercepts_[0])

30

### Case Study2: HR Analytics Case study

In [30]:
import pandas as pd
import numpy as np

In [31]:
# Load the data
hr_df = pd.read_csv( r'C:\Users\DELL\Downloads\3. Deep Learning\1. ANN\HR_comma_sep.csv' )

In [32]:
import matplotlib as plt
import seaborn as sn
%matplotlib inline

In [33]:
# Encoding Categorical Features
numerical_features = ['satisfaction_level', 'last_evaluation', 'number_project',
     'average_montly_hours', 'time_spend_company']

categorical_features = ['Work_accident','promotion_last_5years', 'department', 'salary']

In [34]:
# An utility function to create dummy variable
def create_dummies( df, colname ):
    col_dummies = pd.get_dummies(df[colname], prefix=colname)
    col_dummies.drop(col_dummies.columns[0], axis=1, inplace=True)
    df = pd.concat([df, col_dummies], axis=1)
    df.drop( colname, axis = 1, inplace = True )
    return df

In [35]:
for c_feature in categorical_features:
  hr_df = create_dummies( hr_df, c_feature )

In [36]:
#Splitting the data

feature_columns = hr_df.columns.difference( ['left'] )
feature_columns1 = feature_columns[1:5]

In [38]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split( hr_df[feature_columns],
                                                  hr_df['left'],
                                                  test_size = 0.2,
                                                  random_state = 42 )

In [39]:
# Creating a confusion matrix

from sklearn import metrics

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(train_X)

StandardScaler()

In [35]:
# Now apply the transformations to the data:
X_train = scaler.transform(train_X)
X_test = scaler.transform(test_X)

In [2]:
from sklearn.neural_network import MLPClassifier
#MLPClassifier?
mlp = MLPClassifier(hidden_layer_sizes=(3), verbose=True)
mlp.fit(X_train,train_y)

In [37]:
predictions = mlp.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(test_y,predictions))
print(classification_report(test_y,predictions))

[[2227   67]
 [  82  624]]
             precision    recall  f1-score   support

          0       0.96      0.97      0.97      2294
          1       0.90      0.88      0.89       706

avg / total       0.95      0.95      0.95      3000



In [38]:
len(mlp.coefs_)
len(mlp.coefs_[0])
len(mlp.intercepts_[0])

3

In [39]:
mlp.coefs_

[array([[-0.21969231,  0.01021114, -0.21512697],
        [-0.04378127,  0.4932163 ,  1.15464501],
        [-0.10134856, -0.01028532, -0.08888892],
        [ 0.05288562,  0.01919692,  0.03209407],
        [ 0.0026989 , -0.02264729,  0.07366724],
        [-0.20700317, -1.24429377, -0.30890222],
        [ 0.04221987, -0.003291  ,  0.01678439],
        [ 0.02262135,  0.02853338, -0.06440194],
        [ 0.05098232, -0.02868897,  0.02484327],
        [ 0.07045973,  0.04407326,  0.14015519],
        [ 0.00840395, -0.03365395,  0.0341222 ],
        [-0.32002802,  0.33926015,  0.88181525],
        [-2.15314042,  0.07737459,  0.78741693],
        [-0.15271307, -1.12070171, -1.17594962],
        [ 0.45845865, -0.02707487,  0.52278956],
        [ 0.33439736, -0.01464051,  0.42675277],
        [-0.31855883,  0.672664  ,  0.45129339],
        [-1.69374458, -2.16227647, -0.63949487]]), array([[ 1.82299736],
        [-2.59699317],
        [ 1.92335481]])]

In [40]:
train_X.head(5)

Work_accident_1  average_montly_hours  department_RandD  \
9838                0                   188                 0   
7689                0                   196                 0   
6557                0                   175                 1   
6872                0                   112                 0   
820                 0                   284                 0   

      department_accounting  department_hr  department_management  \
9838                      0              0                      0   
7689                      0              0                      0   
6557                      0              0                      0   
6872                      1              0                      0   
820                       0              0                      0   

      department_marketing  department_product_mng  department_sales  \
9838                     0                       1                 0   
7689                     0                       0                 0   
6557                     0                       0                 0   
6872                     0                       0                 0   
820                      0                       0                 0   

      department_support  department_technical  last_evaluation  \
9838                   0                     0             0.61   
7689                   0                     1             0.78   
6557                   0                     0             0.80   
6872                   0                     0             0.86   
820                    0                     1             0.93   

      number_project  promotion_last_5years_1  salary_low  salary_medium  \
9838               3                        0           1              0   
7689               4                        0           0              0   
6557               3                        0           0              1   
6872               4                        0           0              1   
820                7                        0           1              0   

      satisfaction_level  time_spend_company  
9838                1.00                   4  
7689                0.16                   5  
6557                0.80                   2  
6872                0.66                   6  
820                 0.11                   4